-- MySQL Script generated by MySQL Workbench
-- 08/16/14 18:23:53
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hrms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hrms` ;
CREATE SCHEMA IF NOT EXISTS `hrms` DEFAULT CHARACTER SET utf8 ;
USE `hrms` ;

-- -----------------------------------------------------
-- Table `hrms`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`contact` ;

CREATE TABLE IF NOT EXISTS `hrms`.`contact` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_city` VARCHAR(60) NOT NULL,
  `contact_address` VARCHAR(45) NOT NULL,
  `zipcode` VARCHAR(5) NOT NULL,
  `contact_phone` VARCHAR(12) NOT NULL,
  `contact_phone2` VARCHAR(12) NOT NULL,
  `contact_email` VARCHAR(25) NOT NULL,
  `contact_email2` VARCHAR(25) NOT NULL,
  `contact_internalnum` VARCHAR(25) NOT NULL,
  `skype` VARCHAR(25) NOT NULL,
  `notes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`admin_tb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`admin_tb` ;

CREATE TABLE IF NOT EXISTS `hrms`.`admin_tb` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(45) NOT NULL,
  `admin_password` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`bonus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`bonus` ;

CREATE TABLE IF NOT EXISTS `hrms`.`bonus` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `bonus_grade` CHAR(1) NOT NULL,
  `bonus_sum` FLOAT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`organization` ;

CREATE TABLE IF NOT EXISTS `hrms`.`organization` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_name` VARCHAR(60) NOT NULL,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_organization_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_organization_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `hrms`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`department` ;

CREATE TABLE IF NOT EXISTS `hrms`.`department` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(45) NOT NULL,
  `department_place` VARCHAR(12) NOT NULL,
  `organization_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_department_organization1_idx` (`organization_id` ASC),
  CONSTRAINT `fk_department_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `hrms`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`passport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`passport` ;

CREATE TABLE IF NOT EXISTS `hrms`.`passport` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `passport_snum` VARCHAR(12) NOT NULL,
  `passport_date` DATE NOT NULL,
  `passport_issue` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`worktime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`worktime` ;

CREATE TABLE IF NOT EXISTS `hrms`.`worktime` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `worktime_from` CHAR(5) NOT NULL,
  `worktime_till` CHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`photo` ;

CREATE TABLE IF NOT EXISTS `hrms`.`photo` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `photo_value` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`contract` ;

CREATE TABLE IF NOT EXISTS `hrms`.`contract` (
  `id` INT NOT NULL,
  `contract_number` VARCHAR(9) NOT NULL,
  `contract_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`person` ;

CREATE TABLE IF NOT EXISTS `hrms`.`person` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_name` VARCHAR(45) NOT NULL,
  `person_lastname` VARCHAR(45) NOT NULL,
  `person_middlename` VARCHAR(45) NOT NULL,
  `person_dob` DATE NOT NULL,
  `person_age` TINYINT(3) UNSIGNED NOT NULL,
  `person_gender` ENUM('M','F') NOT NULL,
  `person_citizenship` VARCHAR(25) NOT NULL,
  `person_ident` VARCHAR(10) NOT NULL,
  `person_marital` ENUM('H','W','N') NOT NULL,
  `person_diploma` ENUM('Y','N') NOT NULL,
  `person_jobber` ENUM('Y','N') NOT NULL,
  `insurance_number` VARCHAR(12) NOT NULL,
  `person_tabno` VARCHAR(9) NOT NULL,
  `person_hired` DATE NOT NULL,
  `person_fired` DATE NOT NULL,
  `person_place` SMALLINT UNSIGNED NOT NULL,
  `passport_id` INT(10) UNSIGNED NOT NULL,
  `photo_id` INT(11) UNSIGNED NOT NULL,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `department_id` INT(10) UNSIGNED NOT NULL,
  `organization_id` INT(10) UNSIGNED NOT NULL,
  `worktime_id` INT(11) UNSIGNED NOT NULL,
  `bonus_id` INT(11) UNSIGNED NOT NULL,
  `contract_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_contact1_idx` (`contact_id` ASC),
  INDEX `fk_person_passport1_idx` (`passport_id` ASC),
  INDEX `fk_person_department1_idx` (`department_id` ASC),
  INDEX `fk_person_organization1_idx` (`organization_id` ASC),
  INDEX `fk_person_worktime1_idx` (`worktime_id` ASC),
  INDEX `fk_person_photo1_idx` (`photo_id` ASC),
  INDEX `fk_person_bonus1_idx` (`bonus_id` ASC),
  INDEX `fk_person_contract1_idx` (`contract_id` ASC),
  CONSTRAINT `fk_person_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `hrms`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_passport1`
    FOREIGN KEY (`passport_id`)
    REFERENCES `hrms`.`passport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hrms`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `hrms`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_worktime1`
    FOREIGN KEY (`worktime_id`)
    REFERENCES `hrms`.`worktime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_photo1`
    FOREIGN KEY (`photo_id`)
    REFERENCES `hrms`.`photo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_bonus1`
    FOREIGN KEY (`bonus_id`)
    REFERENCES `hrms`.`bonus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_contract1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `hrms`.`contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`diploma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`diploma` ;

CREATE TABLE IF NOT EXISTS `hrms`.`diploma` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `diploma_name` VARCHAR(60) NOT NULL,
  `diploma_year` YEAR NOT NULL,
  `person_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_diploma_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_diploma_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hrms`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`parents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`parents` ;

CREATE TABLE IF NOT EXISTS `hrms`.`parents` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_name` VARCHAR(45) NOT NULL,
  `parent_lastname` VARCHAR(45) NOT NULL,
  `parent_middlename` VARCHAR(45) NOT NULL,
  `parent_gender` ENUM('M','F') NOT NULL,
  `parent_age` TINYINT(4) NOT NULL,
  `parent_position` VARCHAR(45) NOT NULL,
  `person_id` INT(10) UNSIGNED NOT NULL,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parents_contact1_idx` (`contact_id` ASC),
  INDEX `fk_parents_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_parents_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `hrms`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parents_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hrms`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`position` ;

CREATE TABLE IF NOT EXISTS `hrms`.`position` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(60) NOT NULL,
  `position_hiredate` DATE NOT NULL,
  `person_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_position_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_position_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hrms`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`salary` ;

CREATE TABLE IF NOT EXISTS `hrms`.`salary` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `salary_value` FLOAT NOT NULL,
  `salary_date` DATE NOT NULL,
  `person_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salary_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_salary_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hrms`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`skill` ;

CREATE TABLE IF NOT EXISTS `hrms`.`skill` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `skill_name` VARCHAR(45) NOT NULL,
  `person_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skill_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_skill_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hrms`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`sicklist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`sicklist` ;

CREATE TABLE IF NOT EXISTS `hrms`.`sicklist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sicklist_number` VARCHAR(12) NOT NULL,
  `sicklist_from` DATE NOT NULL,
  `sicklist_till` DATE NOT NULL,
  `person_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sicklist_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_sicklist_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hrms`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`errand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`errand` ;

CREATE TABLE IF NOT EXISTS `hrms`.`errand` (
  `id` INT NOT NULL,
  `errand_from` DATE NOT NULL,
  `errand_till` DATE NOT NULL,
  `person_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_errand_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_errand_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hrms`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrms`.`vacation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrms`.`vacation` ;

CREATE TABLE IF NOT EXISTS `hrms`.`vacation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vacation_date` DATE NOT NULL,
  `person_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vacation_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_vacation_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `hrms`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
