package directhrm.gui.windows;

import directhrm.Application;
import directhrm.db.DbDepartmentManager;
import directhrm.entity.Organization;
import directhrm.gui.GuiUtil;
import directhrm.gui.controller.ControllerOrganization;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author andre
 */
public class DlgOrganization extends javax.swing.JDialog {

	/**
	 * Creates new form DlgOrganization
	 * @param parent
	 * @param modal
	 * @param application
	 */
	public DlgOrganization(
			java.awt.Frame parent, boolean modal, Application application) 
	{
		super(parent, modal);
		this.application = application;
		initComponents();

		panelOrganization = new PanelOrganization();
		panelContent.add(panelOrganization);
		
		fieldName = panelOrganization.getFieldName();
		
		buttonSave.addActionListener( new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				actionSave();
			}
		} );
		buttonCancel.addActionListener( new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				DlgOrganization.this.dispose();
			}
		} );
	}

	public void setOrganization(Organization o) {
		this.organization = o;
		fieldName.setText( organization.getOrganizationName() );
	}

	public void actionSave() {
		StringBuilder sbMessage = new StringBuilder();
		GuiUtil.testFieldLength("Название организации", fieldName, 60, sbMessage);
		if( sbMessage.length() > 0 ) {
			JOptionPane.showMessageDialog(
					this, sbMessage, "Внимание", 
					JOptionPane.ERROR_MESSAGE);
			return;
		}
		Organization o = new Organization();
		o.setId( organization.getId() );
		o.setOrganizationName( fieldName.getText() );
		try {
			DbDepartmentManager departmentManager = 
					application.getDbManager().getDepartmentManager();
			departmentManager.saveOrganization(o);
			dispose();
		} catch (SQLException ex) {
			Logger.getLogger(DlgOrganization.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(
					this, "Возникла ошибка во время выполнения операции", 
					"Ошибка", JOptionPane.ERROR_MESSAGE);
		}
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        buttonCancel = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Организация");

        panelContent.setLayout(new java.awt.BorderLayout());

        buttonCancel.setText("Отменить");

        buttonSave.setText("Сохранить");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 160, Short.MAX_VALUE)
                        .addComponent(buttonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private Application application;
	private Organization organization;
	private PanelOrganization panelOrganization;
	private JTextField fieldName;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
